apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sss.fullname" . }}
  labels:
    {{- include "sss.labels" . | nindent 4 }}
type: Opaque
data:
  password-sss: {{ default (randAlphaNum 16) .Values.somePassword | b64enc | quote }}
  opts-sss: {{ .Values.sss.options | b64enc }}