apiVersion: v1
kind: Service
metadata:
  name: {{ include "sss.fullname" . }}
  labels:
    {{- include "sss.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "sss.selectorLabels" . | nindent 4 }}
